---
services:
  mkdocs:
    image: "ghcr.io/diegoquintanav/dlt-tutorial-mkdocs:${DOCKER_MKDOCS_TAG-latest}"
    build:
      context: .
      dockerfile: Dockerfile.mkdocs
    ports:
      - "8000:8000"
    volumes:
      - ./mkdocs.en.yml:/docs/mkdocs.en.yml
      - ./mkdocs.es.yml:/docs/mkdocs.es.yml
      - ./docs:/docs/docs # needed for mkdocs serve
      - ./README.md:/docs/README.md
      - ./.git:/docs/.git:ro # needed for plugins
      - ./dlt_tutorial:/docs/dlt_tutorial:ro # needed for plugins
    command:
      - "serve"
      - "--dev-addr=0.0.0.0:8000"
      - "--livereload"
      - "--config-file"
      - "mkdocs.en.yml"
