services:
  devcontainer:
    image: "ghcr.io/diegoquintanav/dlt-tutorial-devcontainer:${DOCKER_TAG-latest}"
    build:
      context: .
      dockerfile: Dockerfile.devcontainer

    volumes:
      - .:/app:cached
      - uv_venv:/app/.venv:cached
    command: ["tail", "-f", "/dev/null"]

volumes:
  uv_venv:
    driver: local
