services:
  db:
    # https://hub.docker.com/_/postgres/
    image: "postgres:15"
    restart: no
    environment:
      - POSTGRES_PASSWORD=test
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5555:5432
    networks:
      db_nw:
        aliases:
          - postgres

networks:
  db_nw:
    driver: bridge

volumes:
  pgdata:
